### ISSUE TITLE
[🧪] Make the E2E test run in every new commits to the main branch

### ISSUE THREAD

**Issue by mazipan** [depapp/IndoGitHubers#31]
Now the CI can only run using workflow dispatch which is need a manual click.

Add this block:

```yaml
on:
  workflow_dispatch:
  push:
    branches: 'master'
```

To the workflow file at https://github.com/depapp/IndoGitHubers/blob/main/.github/workflows/e2e.yml#L3-L4
