### ISSUE TITLE
[🧪] Upload artifact playwright report to gh-pages

### ISSUE THREAD

**Issue by mazipan** [depapp/IndoGitHubers#47]
Currently we only save the report to the artifact, to check the report we need to download it first to our local computer.

I think it's better to just upload it to github-pages.

```yaml
  publish_report:
    runs-on: ubuntu-latest
    needs: smoke-test
    permissions:
      pages: write
      id-token: write
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
        with:
          - artifact_name: 'playwright-report'
```

P.S: I'm not sure, need to trial-and-error

Reference: https://github.com/actions/deploy-pages
